version: '3'
services:
  web:
    build:
      context: ./sources-frontend
    ports:
      - "8000:7860"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq

  ocr:
    build:
      context: ./sources-backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"